### ISSUE TITLE
Quy trình quản lý lịch hẹn

### ISSUE THREAD

**Issue by tozydev** [tozydev/virgo-14#10]
Công việc:

> Viết mô tả và vẽ sơ đồ UML Active.

Yêu cầu:

* Các công việc sẽ giúp hoàn thiện tài liệu `SRS.docx`.
* `SRS.docx` và tài liệu tham khảo tại [đây](https://drive.google.com/drive/folders/1NdWmfgmvmID0UyGiYH7Wz6Iz3QYg6vtS?usp=drive_link).
* Tạo ra các file riêng lẻ đối với từng yêu cầu, post link dưới phần `Comments` của từng task.
* Sau khi làm xong, kéo task sang phần `In Review`.
* Lưu các file output ở thư mục thành viên được tạo tương ứng.
* Đối với yêu cầu viết tài liệu, sử dụng `Google Docs` hoặc `Word`.
* Đối với vẽ sơ đồ, sử dụng draw.io hoặc phần mềm có thể xuất sang định dạng `.drawio`.

**Comment by tozydev** [comment]
@hahoang43 Hãy tham khảo https://github.com/tozydev/virgo-14/issues/8#issuecomment-2400191707 để hoàn thành task.
Nếu có nhiều chức năng phức tạp nên chia nhỏ các quy trình ra.

**Comment by hahoang43** [comment]
[QUẢN LÍ LỊCH HẸN.docx](https://github.com/user-attachments/files/17299875/QU.N.LI.L.CH.H.N.docx)
https://drive.google.com/file/d/1OxzwqOibaIs_x3tyqjoTY5zcxB5OAyx-/view?usp=drive_link

**Comment by tozydev** [comment]
> [QUẢN LÍ LỊCH HẸN.docx](https://github.com/user-attachments/files/17299875/QU.N.LI.L.CH.H.N.docx) https://drive.google.com/file/d/1OxzwqOibaIs_x3tyqjoTY5zcxB5OAyx-/view?usp=drive_link

@hahoang43 lưu file trên drive của từng thành viên đã được tạo

**Comment by tozydev** [comment]
- Nội dung mô tả viết ngắn gọn lại (1-2 dòng).
- Biểu đồ vẽ cần cập nhật lại chỗ hủy lịch hẹn. Khi hủy lịch sẽ không xóa mà chỉ cập nhật lại trạng thái là đã hủy.
- Còn thiếu quy trình đặt/tạo lịch hẹn.

**Comment by hahoang43** [comment]
ông thấy draw trang 1 hay trang 2 trông ổn hơn á

Vào 11:13, Th 4, 9 thg 10, 2024 Nguyễn Thanh Tân ***@***.***>
đã viết:

**Comment by hahoang43** [comment]
Quản lí lịch hẹn update : https://drive.google.com/file/d/15KSH0Tm8NddTTqakGLkFxFyfN6V6CSly/view?usp=drive_link

**Comment by hahoang43** [comment]
Mô tả: [QUẢN LÍ LỊCH HẸN.docx](https://github.com/user-attachments/files/17305517/QU.N.LI.L.CH.H.N.docx)
