### ISSUE TITLE
Quy trình quản lý dịch vụ

### ISSUE THREAD

**Issue by tozydev** [tozydev/virgo-14#11]
Công việc:

> Viết mô tả và vẽ sơ đồ UML Active.

Yêu cầu:

* Các công việc sẽ giúp hoàn thiện tài liệu `SRS.docx`.
* `SRS.docx` và tài liệu tham khảo tại [đây](https://drive.google.com/drive/folders/1NdWmfgmvmID0UyGiYH7Wz6Iz3QYg6vtS?usp=drive_link).
* Tạo ra các file riêng lẻ đối với từng yêu cầu, post link dưới phần `Comments` của từng task.
* Sau khi làm xong, kéo task sang phần `In Review`.
* Lưu các file output ở thư mục thành viên được tạo tương ứng.
* Đối với yêu cầu viết tài liệu, sử dụng `Google Docs` hoặc `Word`.
* Đối với vẽ sơ đồ, sử dụng draw.io hoặc phần mềm có thể xuất sang định dạng `.drawio`.

**Comment by HoangHazaLHC** [comment]
https://drive.google.com/drive/u/1/folders/19yqyBYy8idGwTuqK46rxh_FWPMQ32f5e

**Comment by tozydev** [comment]
## Tài liệu

Mô tả ngắn gọn nhất có thể đối với quy trình trên, tập trung vào phần biểu đồ.

Tham khảo: [Template 2.pdf](https://drive.google.com/file/d/16-O-6N_7pqw2VNZjEYAZM5sXoC4k6LFs/view?usp=drive_link)

## Biểu đồ

Tham khảo lại cách vẽ biểu đồ hoạt động (UML Activity Diagram).

![Picture](https://github.com/user-attachments/assets/42f182c9-da73-4b8e-8bed-4807cd129ebf)

**Comment by tozydev** [comment]
@HoangHazaLHC Hãy tham khảo https://github.com/tozydev/virgo-14/issues/8#issuecomment-2400191707 để hoàn thành task.
Nếu có nhiều chức năng phức tạp nên chia nhỏ các quy trình ra.

**Comment by HoangHazaLHC** [comment]
Đã Update: https://drive.google.com/drive/u/1/folders/19yqyBYy8idGwTuqK46rxh_FWPMQ32f5e
