### ISSUE TITLE
Quy trình quản lý nhân viên

### ISSUE THREAD

**Issue by tozydev** [tozydev/virgo-14#12]
Công việc:

> Viết mô tả và vẽ sơ đồ UML Active.

Yêu cầu:

* Các công việc sẽ giúp hoàn thiện tài liệu `SRS.docx`.
* `SRS.docx` và tài liệu tham khảo tại [đây](https://drive.google.com/drive/folders/1NdWmfgmvmID0UyGiYH7Wz6Iz3QYg6vtS?usp=drive_link).
* Tạo ra các file riêng lẻ đối với từng yêu cầu, post link dưới phần `Comments` của từng task.
* Sau khi làm xong, kéo task sang phần `In Review`.
* Lưu các file output ở thư mục thành viên được tạo tương ứng.
* Đối với yêu cầu viết tài liệu, sử dụng `Google Docs` hoặc `Word`.
* Đối với vẽ sơ đồ, sử dụng draw.io hoặc phần mềm có thể xuất sang định dạng `.drawio`.

**Comment by tozydev** [comment]
@yendn281 Hãy tham khảo https://github.com/tozydev/virgo-14/issues/8#issuecomment-2400191707 để hoàn thành task.
Nếu có nhiều chức năng phức tạp nên chia nhỏ các quy trình ra.

**Comment by yendn281** [comment]
https://drive.google.com/file/d/1JxwjXoIJtBZYSud2ckDW2NWWvJC-xCdd/view?usp=sharing

**Comment by yendn281** [comment]
https://docs.google.com/document/d/1WjTj96hbhhodQChPgfKLg0ZM26UBBBk0/edit?usp=sharing&ouid=108122090829861574669&rtpof=true&sd=true

**Comment by yendn281** [comment]
Đã bổ sung phần mô tả quy trình.
