### ISSUE TITLE
Quy trình thanh toán

### ISSUE THREAD

**Issue by tozydev** [tozydev/virgo-14#13]
Công việc:

> Viết mô tả và vẽ sơ đồ UML Active.

Yêu cầu:

* Các công việc sẽ giúp hoàn thiện tài liệu `SRS.docx`.
* `SRS.docx` và tài liệu tham khảo tại [đây](https://drive.google.com/drive/folders/1NdWmfgmvmID0UyGiYH7Wz6Iz3QYg6vtS?usp=drive_link).
* Tạo ra các file riêng lẻ đối với từng yêu cầu, post link dưới phần `Comments` của từng task.
* Sau khi làm xong, kéo task sang phần `In Review`.
* Lưu các file output ở thư mục thành viên được tạo tương ứng.
* Đối với yêu cầu viết tài liệu, sử dụng `Google Docs` hoặc `Word`.
* Đối với vẽ sơ đồ, sử dụng draw.io hoặc phần mềm có thể xuất sang định dạng `.drawio`.

**Comment by tozydev** [comment]
@tduyen73 Hãy tham khảo https://github.com/tozydev/virgo-14/issues/8#issuecomment-2400191707 để hoàn thành task.
Nếu có nhiều chức năng phức tạp nên chia nhỏ các quy trình ra.

**Comment by tduyen73** [comment]
Quy trình thanh toán : https://drive.google.com/file/d/1my7h8thRLt78qGc_DYkOnDcwQQJYD6L3/view?usp=drivesdk

**Comment by tozydev** [comment]
Lưu tại thư mục này https://drive.google.com/drive/u/3/folders/1VVQFeGJw1q7yjaQI6NPkrFAjZKem7ZIQ

**Comment by tduyen73** [comment]
Quy trình thanh toán: https://docs.google.com/document/d/1KaAAymhzwqliWU2aU06revMxD28V8HTF/edit?usp=drive_link&ouid=113063805368318774790&rtpof=true&sd=true

**Comment by tozydev** [comment]
@tduyen73 chuyển sang làm task #16. Task này để tui hoàn thành.

**Comment by tozydev** [comment]
## Changes

<details><summary>Code UML</summary>

```plantuml
@startuml

|Customer|
start
:Đăng nhập;
:Sử dụng dịch vụ;
|Staff|
:Tạo hóa đơn thanh toán;
|System|
:Lưu hóa đơn;
:Thông báo hóa đơn;
|Staff|
:Hiện thị hóa đơn;
|Customer|
:Nhận hóa đơn;
if (Tiền mặt?) then (yes)
else (no)
  :Thanh toán trực tuyến;
  |Payment Gateway|
  :Xác nhận thanh toán;
  :Thông báo thanh toán thành công;
  |System|
  :Xác nhận thanh toán thành công;
  :Thông báo thanh toán thành công;
  |Staff|
  :Hiển thị thanh toán thành công;
  |Customer|
  :Hiển thị thanh toán thành công;
endif
|System|
:Ghi nhận điểm thưởng;
:Thống báo ghi nhận điểm thưởng;
|Customer|
:Hiển thị điểm thưởng;
stop

@enduml
```
</details> 

Preview:
![Image](https://github.com/user-attachments/assets/cedee84c-416e-4c4c-b96e-90c8e45d4648)
