### ISSUE TITLE
Yêu cầu phi chức năng

### ISSUE THREAD

**Issue by tozydev** [tozydev/virgo-14#14]
Công việc:

> Viết tài liệu phần "Yêu cầu phi chức năng"

Yêu cầu:

* Các công việc sẽ giúp hoàn thiện tài liệu `SRS.docx`.
* `SRS.docx` và tài liệu tham khảo tại [đây](https://drive.google.com/drive/folders/1NdWmfgmvmID0UyGiYH7Wz6Iz3QYg6vtS?usp=drive_link).
* Tạo ra các file riêng lẻ đối với từng yêu cầu, post link dưới phần `Comments` của từng task.
* Sau khi làm xong, kéo task sang phần `In Review`.
* Lưu các file output ở thư mục thành viên được tạo tương ứng.
* Đối với yêu cầu viết tài liệu, sử dụng `Google Docs` hoặc `Word`.
* Đối với vẽ sơ đồ, sử dụng draw.io hoặc phần mềm có thể xuất sang định dạng `.drawio`.

**Comment by HoangHazaLHC** [comment]
File.doc mô tả Yêu cầu phi chức năng của HTQL HairSalon bản rút gọn đầy đủ:
https://docs.google.com/document/d/1fQnw3WiIeyP-cZHTgRPGC7xCrSgH145X/edit?usp=drive_web&ouid=100322126999185575556&rtpof=true

File.doc mô tả Yêu cầu phi chức năng của HTQL HairSalon bản chi tiết :
https://docs.google.com/document/d/1onIkBPLRJLovPUy2-4pEcwHmQwmjCQnB/edit?usp=drive_web&ouid=100322126999185575556&rtpof=true

Nguồn lưu:
https://drive.google.com/drive/u/1/folders/1ZpnJ5nyaPZGl5feCAI7bQaOClTSSDByL
