### ISSUE TITLE
Vẽ biểu đồ luồng dữ liệu cấp 2 (2-level Data Flow Diagram)

### ISSUE THREAD

**Issue by tozydev** [tozydev/virgo-14#18]
> Vẽ biểu đồ luồng dữ liệu cho ứng dụng Hair Salon Booking.

## Tham khảo

- https://www.geeksforgeeks.org/levels-in-data-flow-diagrams-dfd/
- Lưu sơ đồ tại thư mục của các thành viên tại [đây](https://drive.google.com/drive/u/3/folders/1IDgMv0WtO77qPxxEpt0auU8RuG5ZkXgA).

**Comment by tozydev** [comment]
@hahoang43 @Tmy175

**Comment by hahoang43** [comment]
My đưa lên sau á.

**Comment by tozydev** [comment]
bổ sung thêm luồng dữ liệu của khách hàng khi đặt lịch

**Comment by Tmy175** [comment]
https://viewer.diagrams.net/?tags=%7B%7D&lightbox=1&highlight=0000ff&edit=_blank&layers=1&nav=1&title=Bi%E1%BB%83u%20%C4%91%E1%BB%93%20kh%C3%B4ng%20c%C3%B3%20ti%C3%AAu%20%C4%91%E1%BB%81.drawio#R%3Cmxfile%3E%3Cdiagram%20name%3D%22Trang-1%22%20id%3D%22nDos0YWa9icgH21LiK62%22%3E7V1Zl5s6Ev41fuw%2BSEIsj146yZyb3DMzybmTPBKbtplg48G4031%2F%2FUggYbRgY2MQdtIPCYskA1VfqTaVRmi6fn2fBtvVp2QRxiNoLV5HaDaCEHieRf6jV96KK57vFBeWabRgjQ4XPkd%2Fh%2Bwi67fcR4twJzTMkiTOoq14cZ5sNuE8E64FaZr8FJs9J7H4q9tgGSoXPs%2BDWL36n2iRrdhbQPdw%2FUMYLVf8l4HjF3fWAW%2FM3mS3ChbJz8ol9DRC0zRJsuJo%2FToNY%2Frx%2BHcp%2Br2ruVs%2BWBpusiYdnL9evn1ET%2FDl2wf0NHfS7WQ6fWCj7LI3%2FsLhgrw%2FO03SbJUsk00QPx2uTtJkv1mEdFSLnB3afEySLbkIyMX%2Fhln2xogZ7LOEXFpl65jdDV%2Bj7CvrTo%2B%2F0eNHzM5mr5Vbszd2Ujwnfbja1%2BfvkuzTeXjknTFjoyBdhtmxbwNLKhH2DpN1mKVvpGMaxkEWvYgPEjA%2BW5btWNdxmgZvlQbbJNpku8rI%2F6QXSAMGGRugYkQGGATtKlnJQTEiP6s82uFSTvoz2AAWP%2FkSxHv2WtP9ZklhNXoCo8l4NMZb%2BslWoykaTez8VhZtRtAJ1oTmk8333bYkksRMH4PvRCYIDBDE0XJDjueEdmFKLryEaRYR0I3ZjXW0WBS8Fu6iv4Pv%2BXiUDdjXI4PjyQjPyt%2BkA4SvI41EYJ0POKyyTD0mVLKz0a1HG%2FmeQCL29c7jiwPheZPk%2BXlHGFIk9lXIi0yiHFRQDo5inJAlfft6EAb09Fv13qFbfmZSNngtZYNA4nPpaStw%2FUaBOR7vq5B16dkiP5uMvMl8Rbuw0zG%2BD6yiE1i1AIKiOB06VrFCWyJlY%2FINJs9J%2FggHkjn%2F2yf8xsMux%2BGYNID29jX%2F2Pw%2BOVrS%2F9%2Fvw13GRyMPVwxY3FPYQcT%2Fz1WUhZ%2B3QQ6en0TVE5mklrAKBmtpZTu2SCiLKVI%2FD2oXsJjyuKqoXDbsCGXOUKRmj7rRdXQeRanBED865M9zLQBcYhWIpLa9R0T%2BsOc6hA082xbHL6QxG%2FL6iHMVxL3nUnIW5e9AZSuYk8PNigvX2eY%2BBKhzStmxJFzyzzVcCeqZxO0Bq%2BfoO4K2c1B%2Butd3AGyo8MC2gqGVKPYViH6tA6U1mtojH9B%2FPZQbKj%2FyprP7wGuN3slGf7Aeoee6ImDtdoB903boDr7c82N%2B3m1srUBT5kp%2F8L3Il4Et0ZdhI1TlmJPtHegdbe9wfVDfvhtfCQCKMPo4mjqjibXXukjuQeoAS88%2BpZoAbCRJHTx0NYFjp2pp0anD0k0dp%2FxccRxtd2EvhhLyJEPJZ5%2B6Yii5rIlgJ%2BGOJmcwGPfSKUOpFNnAnMLlNZTY2KS%2BBVQP04eIe5LQppBz3LF0%2F14mcNzNRLQu2%2BY%2B4QELPD01DAR7hm8WNUVpnazuCaaORhXhAZu347i8y8hNjdA84BQ5tuTOcAYPW3co0%2Bv9wBa1Dd9cZA55QPR72vi4OSS3x8iRGKwL88ZTZMqXXAuerqlCHDH5Mnm3Pm%2Fe71FDxlJ81uZmYkVD9jSRBNyZhuwbnXmZf4IryX3FElrPjTVGP0aPwILY9mwMMTF%2FRFo7SByw4%2BABn5uqcEn5HIwqmPDAL6An%2B6fmXwCh5CeA7eZfPjSQyN7dfAxV%2F88fq6RC3PE7ckLEHad1HoefiZT%2Fq57yu1WwpYfka2dREP%2BbUmKzjBuIzjh8zhi1UybV6PFzFMfTJE4Iu8w2ySa8jpB1XFGRwo4qZAHnnKqUdayOpCxUHTo6woh0%2BWPFAgmUKsWxRV0%2Ft0kU7IoOUU8z8%2FVMFKPOoUuMzkfXlDcfNs0%2BMmt1QtU5NC0jcDRNsBKQy349IxSeykmyoX1rvnKoZiX9a19qOdQfGHNP%2BTFyk5NcwBY8Qg8h7fsSFdlrmmBJj1aDh6VgFbYU2dmr1QCNJiBdlshgLHGTq5WnTX%2FXqOxUk42k9L7ngL0nz977Ry7kiIglXyHY7B52YRo9q8l9fJjdNtgITFOXJQjynCuWKmjl%2BHrYUYA9zJM4DnLY0YZbIkTD9KXQUORf%2Ffy2y0LqCRgv1nk%2BOM8tLB5DfLShpRwCS4o3E6NSoy7pMA%2B74g%2BzyUtVN8HwY2moKebNZmtDs96f86X4DVD0Or6lcx24vgdEFcE6np8it8d%2BDw5cpPFIrcLCDqapKTg6bhLfhQ5%2B0hGFLFuU%2FS118L6z5JDZlXuXKIe3IFagCbECLEc0CL0%2BAj18YcytyYk6oXBCFTyCoiO2OoaSm7Olu7oHwTCYbKzjYsEEvFuHfVvpgUj1m%2F16gDuZSWUBZ%2FCZVMhoJtVFGY%2FmkjIao9Ou4Y2e0KnmUv166DyZP2VByUvadnVJD2DVrO8rHM6AOq52xSF9ljKl1R1VElx9oIkH9umYBha0H7Hw1ZHDRjHlm%2FbMhvVYjO5W8tJQ07w0p8Zu7UkEqqlfpwPofzYK5NxI%2FBwAIGU1WOriin4D6Mis9%2FAypBkLA%2FFiAANXNmzVR%2Fc1D6NkRYCU6hrzAlizzepOlIuTPjnLsaSlTe10izI3TOzRnaph30w5rVuCKmy7FOoypxz0pODgicWrZWU7fftunHj8I95LPPlTsAmW9PFuK5CMpIXIpegyFkjm0Y2zdLkvjWafW9HlEBa96uUSZWO6nGMmum%2FeAOKLrk4bQEazc1xVLTNBMCMf3qjlaauu8atVPZvvdxl5zHS4kwe3Bpiccrn8MSanbNUXquJgsxjT%2BrrU3oiD3S6ai19G%2FIw3mmHUGD64pkBGhYRYQ0F%2BraWFU1ZZ5nVQXIkzihdVFkFplF7%2B42wk35ZGqllOdbZ2LTO9L1Yv7kZbxhr5XpT8YIsa3axQfZjn1x1U4Q8AeCYZ%2F2aWKih8DZfJNLyeF9jI9HhNexf0J0u4qj%2FQ3DYAkOh88SwBkUoH93j7jhCs2rslXL28%2FNswlySTr4ukGI4HVfTyfEHdHHF99A6mHsgtoBc1RG9RncmUIo1Vs38q4mN4C2%2FIvCZKEleDDGAdUZ%2Bu%2FxlVe%2BS09%2BSjKHn4IriJf7vhMEfS0jDSUKZX0wSrK9FU5r3MNHlsXiXhlgRSXdJbP6YJwBILOZ7EGo1tE%2BxLIyFppI5LPeDurOIbYz2rIesV2tpv1mvPerplg78k6zU1onBNfP83650bs1A1SpX1bsonjhtnY9U49fpR5XndfUPBInNO18b0wUZjFljNlqutiaBWhbbmRd6paJGZtMIcKAoanX9Cq%2Bt3ZoU5g3FQXJb31ue86DfEDKxRybp1LjpIzI%2FwcQ%2B5MfybNK1Tc7p0e59wxBIcfaCBI%2BgVjkbqkVwRJK3n87pYlhR%2B82USXCtoVvIA%2FyF0fP250gFY9nGnvvIuco9uoMrdRXJgDvBIXL76Zi3A9UeJXl%2Bz%2FKZPqLoyWYAmaVwH1c5K8vPlIV3bi4NfedE8gG%2FWS%2BZYkvLlSyKkc3vxbGFkO9Ij9yEoPKOrIa6x14TbI%2Fc7TZdeejXbwHUccnYlXnWZQKxlbrkDdHrY8MdRnW9%2FiluOHcra7cqdA0eVYBHOVcpiRjtso7FmOifdOojPc%2B9oyyHlnMhWoTY216tV6Jrxi%2BhEwNBnP6epVeiaSTmxgTxXCXudn%2B4gFVTSdMBtO4giqRsJ4w6nnsD9sHRbR0c7ITWYzYMvUdF7dFw1p6fRBZuO6kuqdfbGR%2FJAhjS1IyRJX9iwWDjPjrk%2Bagaz1c0N1FVxQUPkYKMZaa7qiviyytUE1cMzJHTYrqQIQNWp02%2BytXV74JB2xu1xXnHhbaADKujICwEMGgmeOk%2F0iwSjy%2BwvRIIxIDTNEzQMBDXN5AN3n7hvwwKAo9kZoF8AaHbgELO8D9WrZjRysowCs%2BFMX9Y1dWsce41mekZ1zRvbXYFL%2FIELEX8wmw2dmhhM0MZv6%2BRrRxujOxtcY9IeIt58o%2FUSgPW74FEHRGVrnXp3x8urfZC4JluTLALwsQ4dhYB1yzCuVCvicxY8Pw%2B2UIRMH32VIY0S1dlqLN9shuYVdiHoMxzvN%2FXYmS1OyB9T2AGauboBXQRZ5Emi4ODDmzrkVmF3BLRilEVIlqc3m06ilOKFyClXYRszPHzDBT0vMjyM%2BfH8YW%2FdAS0pIwVY3vFJ05FKxckdupk0%2FZP7zp2cNEHdpMkql6pLHH7U7K0rOzebTbd9Cg6iIohktTUFt4Gtm2r9znRteHNyw%2BBcW9YLGPimIOVzqqWAVUCtkmB0KFPvo%2FyWdiHRkOIHUEoULVPMO5iCyWmaUOl0EJ7knVafkgUtlvz0fw%3D%3D%3C%2Fdiagram%3E%3C%2Fmxfile%3E![Image](https://github.com/user-attachments/assets/baf8813e-ab58-4b56-b07d-9dd87ffbfe75)

**Comment by tozydev** [comment]
bị lỗi file ko load đc. xem lại file nha

**Comment by Tmy175** [comment]
![Image](https://github.com/user-attachments/assets/7883eb95-5eb1-4468-a931-c74c9d88e924)

**Comment by Tmy175** [comment]
https://drive.google.com/file/d/1dzS3yXq0pwnhOHGXBEfN6eJ0fH6_YABw/view?usp=drive_link
