### ISSUE TITLE
Vẽ biểu đồ quan hệ thực thể (Entity Relation Ship Diagram)

### ISSUE THREAD

**Issue by tozydev** [tozydev/virgo-14#19]
> Vẽ biểu đồ quan hệ thực thể cho ứng dụng Hair Salon Booking

## Yêu cầu

- Khách hàng và nhân viên là 2 thực thể khác nhau.
- Phải có lịch sử đặt lịch, sử dụng dịch vụ.
- ...

## Tham khảo

- https://www.lucidchart.com/pages/er-diagrams
- Lưu kết quả đầu ra tai thư mục của thành viên tướng ứng tại [đây](https://www.lucidchart.com/pages/er-diagrams).

**Comment by HuynhSang2005** [comment]
Biểu đồ quan hệ thực thể: https://drive.google.com/file/d/1FFUG3IHbYnSonL8wVF-Fd6ipqMvmnIGK/view?usp=drive_link

**Comment by tozydev** [comment]
![Image](https://github.com/user-attachments/assets/809ceb7c-c272-4a91-82eb-9db34c1d76e5)
này là gì?

Primary Key, Foreign Key?

**Khuyến khích:** https://mermaid.js.org/syntax/entityRelationshipDiagram.html

**Comment by HuynhSang2005** [comment]
mermaid :https://drive.google.com/file/d/1KrXechVDGu9T6ImDgDvGr5xjcLqVphpv/view?usp=drive_link

**Comment by HoangHazaLHC** [comment]
@HuynhSang2005 cái services chưa có relationship à ?

**Comment by HuynhSang2005** [comment]
**Update:**
- mermaid: https://drive.google.com/file/d/1u3HWR-ZLovp7xSucdHcjh6ZeZR8Wom02/view?usp=drive_link
- img: https://drive.google.com/file/d/1-lUIUMR_S19jl9QI3fmHxA8eh8PZbfbK/view?usp=drive_link

**Comment by tozydev** [comment]
chưa thể hiện rõ các mối quan hệ

**Comment by HuynhSang2005** [comment]
**Update-2:**
- mermaid: https://drive.google.com/file/d/1ZAtOPK8AG_QGcP4oXxfnfdaN8Ne1PIDf/view?usp=drive_link
- img: https://drive.google.com/file/d/1SEdRATlVe05J_sOwU1jr__rcTqVj7Hif/view?usp=drive_link 
![bieu_do_quan_he_giua_cac_thuc_the](https://github.com/user-attachments/assets/e896b972-00d7-419a-a7bd-eaf25f4515d7)
