### ISSUE TITLE
Yêu cầu tương tác ngoài

### ISSUE THREAD

**Issue by tozydev** [tozydev/virgo-14#2]
Công việc: viết tiếp tài liệu phần **Yêu cầu tương tác ngoài**

Yêu cầu:

* Các công việc sẽ giúp hoàn thiện tài liệu `SRS.docx`.
* `SRS.docx` và tài liệu tham khảo tại [đây](https://drive.google.com/drive/folders/1NdWmfgmvmID0UyGiYH7Wz6Iz3QYg6vtS?usp=drive_link).
* Tạo ra các file riêng lẻ đối với từng yêu cầu, post link dưới phần `Comments` của từng task.
* Sau khi làm xong, kéo task sang phần `In Review`.
* Lưu các file output ở thư mục thành viên được tạo tương ứng.
* Đối với yêu cầu viết tài liệu, sử dụng `Google Docs` hoặc `Word`.
* Đối với vẽ sơ đồ, sử dụng draw.io hoặc phần mềm có thể xuất sang định dạng `.drawio`.

**Comment by tozydev** [comment]
@Tmy175

**Comment by Tmy175** [comment]
[yeu-cau-tuong-tac-ngoai.docx](https://github.com/user-attachments/files/17343509/yeu-cau-tuong-tac-ngoai.docx)
