### ISSUE TITLE
Vẽ biểu đồ triển khai (Deployment Diagram)

### ISSUE THREAD

**Issue by tozydev** [tozydev/virgo-14#20]
> Vẽ biểu triển khai cho ứng dụng Hair Salon Booking

## Tham khảo

- https://www.lucidchart.com/pages/uml-deployment-diagram
- Lưu kết quả đầu ra tai thư mục của thành viên tướng ứng tại [đây](https://www.lucidchart.com/pages/er-diagrams).

**Comment by yendn281** [comment]
https://drive.google.com/file/d/1jxeyVpf5cf8gdoNRopRY2ZorIaEKWfod/view?usp=drive_link
