### ISSUE TITLE
Vẽ biểu đồ UML Use case: Các tác nhân

### ISSUE THREAD

**Issue by tozydev** [tozydev/virgo-14#3]
Công việc:

> Vẽ biểu đồ UML Use case: Các tác nhân

Biểu đồ Use Case sẽ thể hiện các actor tương tác với hệ thống như thế nào. Ngoài ra còn thể hiện các mối quan hệ giữ các actor.

Yêu cầu:

* Các công việc sẽ giúp hoàn thiện tài liệu `SRS.docx`.
* `SRS.docx` và tài liệu tham khảo tại [đây](https://drive.google.com/drive/folders/1NdWmfgmvmID0UyGiYH7Wz6Iz3QYg6vtS?usp=drive_link).
* Tạo ra các file riêng lẻ đối với từng yêu cầu, post link dưới phần `Comments` của từng task.
* Sau khi làm xong, kéo task sang phần `In Review`.
* Lưu các file output ở thư mục thành viên được tạo tương ứng.
* Đối với yêu cầu viết tài liệu, sử dụng `Google Docs` hoặc `Word`.
* Đối với vẽ sơ đồ, sử dụng draw.io hoặc phần mềm có thể xuất sang định dạng `.drawio`.

**Comment by HuynhSang2005** [comment]
Link UML use case từ draw.io hoặc trong thư mục member/Sang:
https://viewer.diagrams.net/?tags=%7B%7D&lightbox=1&highlight=0000ff&edit=_blank&layers=1&nav=1#R%3Cmxfile%3E%3Cdiagram%20name%3D%22Trang-1%22%20id%3D%22brFEfHS1EAHGWtcRT6J-%22%3E7VrbkuI2EP0aHpnyHXgcYDZbqdmqqUyS3X1KCVsYbWTLkcUtXx9Zkm%2BywUxhw0ySJ1Dr3qe7ddTyyF5Eh58oSDZfSADxyDKCw8hejizLsi2T%2F2SSo5S4s5kUhBQFUmSWglf0N1RCQ0m3KIBprSEjBDOU1IU%2BiWPos5oMUEr29WZrguuzJiCEDcGrD3BT%2BhUFbCOlU2tSyj9DFG7ymU1P7S8CeWO1k3QDArKviOynkb2ghDD5LzosIM6Ul%2BtF9vt0orZYGIUxu6TDj5%2FN3yfH6dj%2F4ytMzO%2Fb2dNkP7YdtTh2zHcMA64AVSSUbUhIYoCfSumckm0cwGxYg5fKNs%2BEJFxocuEPyNhRoQm2jHDRhkVY1co5s4lO7kWJUrKlPjy3AWUTgIaQnWtXqpzbKiQRZPTIO1KIAUO7%2BkKAMpqwaKe6PlIKjpUGCUExSysjv2QC3kDZ%2F9gzFPrK%2FC1PA6mzg1vrwP%2FINeSlymZKkUD%2BDVZgySl3AG%2BVIhpWUcd8v0EMviZAQLPnnt%2BG7w5SBg%2FnEW4CkivCndYVYSrNGfvSDe28zabigoXDtaFY0ePb1WS3qMnDfNr5iv8Jmdi5FKyJQLVUoPfXluQV41Q4xiNvYDrJQXZT9flAnwGivP4VYBLng%2FJFy3Hrc3FxZX7dmzHmoRJ2YwbSRMbPNTpkOM%2FXCOMFwYSKgewAwOna5%2FKUUfInrNR4%2FhSu1j3B7ria%2FRtN2E2nBfZC2DvsZtMbbhAj4QGxb1n3B1eVvtdKy4MaWxSOlcILpIjvHFIl6zHazvoIos2gZ2tBz3Rn9TFkeFfdNDh7iH%2Bzbsd%2BDCIUZw55TBmM2l1PygK000Ur2uKztXaafXGukGR%2FtxF%2B9FnmaPPMrRDnJc9gBfELSRFDPDLYyxVhjESVBo8YhVkFIwNEZcea1pByWoJyi3N6g%2Fnm2Zh8Qfz1TsTfczhrYHF1Mi2WKgh8rlZIW7CJUBDgU0G5HjqyBasgYXq9odh9tnotMNqDweg2YJR2%2F2Ecw9R5m3Vvz%2FDucmrFfO3ZsWU%2BGIaTC%2BTJ5RizXFAeXqJ0rJYGPL5yM%2Bu8LVhXnnPXITe5Ic%2FcIe4w1xDMYaNfL6457XbNm0Y764KLhOAbKM0U%2BO9AwZppZ04Lsb8tCpO7BMj3SOtzUtedRbkyLnYkUfrm9ZbT7WhfQAzCC73s3bKPBi1vS5bckn04d8krFuxD%2BVPJPYrinZjH5R420BXbs09Q%2Fo4r9pszno42kWO41fEu6GB1dPDM2XUdzHoSdpicar6rc7Hnt%2FSjB56Jnq6797XHbiPPmjYximGRyMxfdUwt5RkT0SinURiu2TkSlXL%2BhOLwVxGpxmYpeRYdl3Yp%2BUWpwRYhjwEGVmJlWcjBGppUtp0rt%2BPLd%2BcjdykklC1IzDcBkAALgpTtYcoaKVoUb3hgYz0hrufli5e6aoK2DfKC8PWP%2BfScq11xOaIwfC8UvJoGcvqCUnde221AeVNKbl%2BQiH1lYL3%2B2EHT05%2B27HuzNa87aP5n70bOhcxNUrwBHkdmGrefaGYgt9Bgbm0j1e3O1p%2FMeuOAeVpeW%2FLFK9M6DPTqffrYuDqt1ghbkbhmnns3aiTfPlyKR39WKFC913ninEaYc7HsOS%2Fg7GuMtz4Kxj5Xfr7TAs5JBg%2BIMn0pEdMFwhLqohxsDp88rOodrEWjQ9ugkulNqsupLZgdk7pxgiTBHH5xplmfdnHwIBo%2BCMu53ESLVZ8zVam%2FAUyVQu5eFUbcZL7ZwZEqKtQgu4q2tzD5XhjTRL%2FctpBf46YmfpoyDWri%2FOa643cZPv7IXcT%2BNuX8SRDlD2HqldU3nugre%2FnfARr3fc0BzJb7fttHWYN9nJNfYd5JonF03zRjfoEa%2FnPIE6DxYvlFqyRq5XfB9tM%2F%3C%2Fdiagram%3E%3C%2Fmxfile%3E

**Comment by tozydev** [comment]
@HuynhSang2005 xem lại cách vẽ biểu đồ use case, chú ý các mũi tên.

**Comment by HuynhSang2005** [comment]
Update: https://drive.google.com/file/d/1S-ccer6c6moL6UPpQpIHaIySmb_aFQfM/view?usp=drive_link

**Comment by HuynhSang2005** [comment]
Update biểu đồ UML Use case Các tác nhân: https://drive.google.com/file/d/1S-ccer6c6moL6UPpQpIHaIySmb_aFQfM/view?usp=drive_link

**Comment by tozydev** [comment]
Đã chỉnh lại và render bằng PlantUML
![Actor UML Digram](https://www.plantuml.com/plantuml/svg/POxDIiKm48NtynH3zta1SN5B2xfnLNo0ePtMG7vaPYA8-ExMc53XxYRVoVauDpKIAp50uDtGCee_tWmtBxoQpmc0Lik2JuNLsZqLjHnP02h5HrTBxb_mswPq1CRbKuqZVW5YKLv96OTdye8BXPm69CNN2Rwxoxdp-O0VNhr1ztLw2g0FMepslTqlbEXWWSgkEHqtxihxdoPM3Ys-uqqwjENZ5dtoQa8dhNl76M2Shnwr7onmuxIL67u0)
