### ISSUE TITLE
Use Case tổng quan

### ISSUE THREAD

**Issue by tozydev** [tozydev/virgo-14#4]
Công việc:

> Vẽ biểu đồ UML Use case tổng quan

Yêu cầu:

* Các công việc sẽ giúp hoàn thiện tài liệu `SRS.docx`.
* `SRS.docx` và tài liệu tham khảo tại [đây](https://drive.google.com/drive/folders/1NdWmfgmvmID0UyGiYH7Wz6Iz3QYg6vtS?usp=drive_link).
* Tạo ra các file riêng lẻ đối với từng yêu cầu, post link dưới phần `Comments` của từng task.
* Sau khi làm xong, kéo task sang phần `In Review`.
* Lưu các file output ở thư mục thành viên được tạo tương ứng.
* Đối với yêu cầu viết tài liệu, sử dụng `Google Docs` hoặc `Word`.
* Đối với vẽ sơ đồ, sử dụng draw.io hoặc phần mềm có thể xuất sang định dạng `.drawio`.

**Comment by tozydev** [comment]
https://drive.google.com/file/d/1cYj-lOHhhCR-e0pJRqA-jI9C1uMzCFky/view?usp=sharing

**Comment by HuynhSang2005** [comment]
Mình thấy cập nhật thông tin cá nhân nên là use case con của quản lý thông tin cá nhân:
- Quản lý thông tin sẽ có 2 use case con là: cập nhật thông tin và thay đổi mật khẩu

**Comment by tozydev** [comment]
> Mình thấy cập nhật thông tin cá nhân nên là use case con của quản lý thông tin cá nhân:
> 
> * Quản lý thông tin sẽ có 2 use case con là: cập nhật thông tin và thay đổi mật khẩu



## Changes

<details><summary>Code</summary>

```plantuml
@startuml
skinparam usecase {
  BackgroundColor BUSINESS
}

skinparam note {
  BackgroundColor LightSkyBlue
}

left to right direction

actor Guest as G
actor Customer as C
actor Staff as S
actor Manager as M
actor "System Administrator" as AD

G <|-r- C
S <|-r- M

rectangle "System" as SS {
  note "Quản lý thường là CRUD\nCRUD: Create, Read, Update, Delete" as N2

  usecase "Đăng nhập" as UC5
  rectangle "User" as F {
    usecase "Tìm kiếm dịch vụ" as UC1
    usecase "Xem dịch vụ" as UC2
    usecase "Sử dụng trợ lý ảo" as UC3
    usecase "Đăng ký" as UC4
    usecase "Quản lý lịch hẹn" as UC6
    usecase "Đánh giá dịch vụ" as UC7
    usecase "Quản lý thông tin cá nhân" as UC8
    usecase "Xem lịch sử đặt hẹn" as UC20
  }

  rectangle "Admin" as B {
    usecase "Quản lý lịch hẹn khách hàng" as UC9
    usecase "Xem lịch sử làm việc" as UC10
    usecase "Cập nhật trạng thái" as UC11
    usecase "Tạo hóa đơn thanh toán" as UC12
    usecase "Phản hồi đánh giá" as UC13
    usecase "Quản lý dịch vụ" as UC14
    usecase "Quản lý nhân viên" as UC15
    usecase "Quản lý tài chính" as UC16
    usecase "Báo cáo và thống kê" as UC17
    usecase "Cập nhật thông tin salon" as UC18
  }
}

F -[hidden]- B
N2 .r. B

G -d- UC1
G -d- UC2
G -d- UC3
G -d- UC4
G -d- UC5

C -d- UC6
C -d- UC7
C -d- UC8
C -d- UC20

S -u- UC5
S -u- UC9
S -u- UC10
S -u- UC11
S -u- UC12
S -u- UC13
S -u- UC14 : xem

M -u- UC14
M -u- UC15
M -u- UC16
M -u- UC17
M -u- UC18

AD -- SS : administer
@enduml
```
</details> 

Preview:

![PlantUML SVG](https://www.plantuml.com/plantuml/svg/ZLHDQzj05BplhtZu78N4ZcCdz91ORaoX2MrKGw7jOP4sbh2q2j8gDAGvzT13Bmqz5-o6N483XHPABK8F2laV-YTzgu-LxTgX5pDwcdcQsHsy4meQYCXpIJXq-34Dg0THo4mQCZWZ01rg3WU17t5Bzrq_W4xVU7Bms338EPbIS5yifZzr1hOmXgSTDs9Iuh8Z0SA7GCx1SW9c2iVdX51J8BqNiL003Q5N3FGe5Bx70ZdJYvaXwD6H71Z5O9zoEiWv-yMePfo6WdcmQtaETq8HK9pM96EtIqWF7htJ0Wqt6Zb27P5MA1-uh1HdTCEGkVA0jUTHEhdau2Qt8EpxxsdyXG_mQGJwOR_xcilVRT03HWLRWKD6hHNe7rlPKvUvJB1ivK6T4527NBlxTFSUrt0xdTmSPuI-taJ2b9z-o7BpUvcPAV6Bv9i7GoUT_F70IkEFfWqdQNnLh5cV9RzaYqZrMPAHnZUITOMUH936brbSpEqN_COqNzaV9hV5-usfzxDdvkRVng2_UK7Ud5-MZBaD0oSPBt3QMhfPsCbFwTVXOAAKsydNyWljVywWz17Af7SNwUINcF5KNqF9EPcz0bcadD21i_zA24Cx6Sk7PCG7nUgjXyrWbJmuSTBuWrdUuDgiGfSboRiYvFLCnZ8sViWf1Ujp1K6AZnv-K8nwF-P8fjm6uUD1bvAv1Zopipns6dzsKAHkfAGtbiLVrC2bRSWl2TCcryf8S_a59oC7J3kvuNP9dgjE9y6SflmvIKOWqFr5Lilhajzww2Ih_eJKzPMXTjO4xC8UQAzinx8OVwD1XnpKOJLOHK1we5cQf2fKLwYXq8P2JKBq0cugr5AehH2sa1YWHPb8eIs5i1aAhbUmNi561JTW6zuoZv1zDQbWiuAR5MnLi4t8RXSq3Gm3zz3YBvK5P8TnA_BSlm00)

**Comment by tozydev** [comment]
## Changes

- Loại bỏ MQH use case "Đăng nhập" của Staff.

<details><summary>Code</summary>

```plantuml
@startuml
skinparam usecase {
  BackgroundColor BUSINESS
}

skinparam note {
  BackgroundColor LightSkyBlue
}

left to right direction

actor Guest as G
actor Customer as C
actor Staff as S
actor Manager as M
actor "System Administrator" as AD

G <|-r- C
S <|-r- M

rectangle "System" as SS {
  note "Quản lý thường là CRUD\nCRUD: Create, Read, Update, Delete" as N2

  usecase "Đăng nhập" as UC5
  rectangle "User" as F {
    usecase "Tìm kiếm dịch vụ" as UC1
    usecase "Xem dịch vụ" as UC2
    usecase "Sử dụng trợ lý ảo" as UC3
    usecase "Đăng ký" as UC4
    usecase "Quản lý lịch hẹn" as UC6
    usecase "Đánh giá dịch vụ" as UC7
    usecase "Quản lý thông tin cá nhân" as UC8
    usecase "Xem lịch sử đặt hẹn" as UC20
  }

  rectangle "Admin" as B {
    usecase "Quản lý lịch hẹn khách hàng" as UC9
    usecase "Xem lịch sử làm việc" as UC10
    usecase "Cập nhật trạng thái" as UC11
    usecase "Tạo hóa đơn thanh toán" as UC12
    usecase "Phản hồi đánh giá" as UC13
    usecase "Quản lý dịch vụ" as UC14
    usecase "Quản lý nhân viên" as UC15
    usecase "Quản lý tài chính" as UC16
    usecase "Báo cáo và thống kê" as UC17
    usecase "Cập nhật thông tin salon" as UC18
  }
}

F -[hidden]- B
N2 .r. B

G -d- UC1
G -d- UC2
G -d- UC3
G -d- UC4
G -d- UC5

C -d- UC6
C -d- UC7
C -d- UC8
C -d- UC20

S -u- UC9
S -u- UC10
S -u- UC11
S -u- UC12
S -u- UC13
S -u- UC14 : xem

M -u- UC14
M -u- UC15
M -u- UC16
M -u- UC17
M -u- UC18

AD -- SS : administer
@enduml
```
</details> 

Preview:

![PlantUML SVG](https://www.plantuml.com/plantuml/svg/ZLJ1Qjj04BtlLmm-Ho6nuzW9FIIM6rEeGnlLK6XxMAID92ojWhGA3MbEFVJGIqFFXRWXbz10eOLIcz23Glv3Vz9PUILPhXrw4K-ZDxFlxJnx9n8q5B7laMZeyYCQKX_YY9aqOd1A03hK7DfX47DB3xmWXCx0UBB_s3386Pdfu85OJ7_gseumXYSTBsQonME70aG0eQo3vORC56x02Q6cG7elPf406a5F5VGu4e7FGbdJLSqGzF1G5WnLw5DExIcdhqeruoGIp8TTotUv6ucGOhKc6RjTGdhmw9qMQZZHKAXFY9H2kUsnl3cZ6uRqDJLOUnwduqiENd8Bmhd_daw-S1lVBa0_67HVS_dS1ZraLB0LE63KMe71aPMzTPd71Cj6xjS9WUAIQtUVxjxZ6EwauvkZZ33GcqYOqJE8s5JyNYPcflb5yis7ePkE__XWfPEFfWF7wUHAZLclab-oHQHwbMIaanl9kk8sY32TN6PsqNUW-8qgNyaV9hVg-yRCz-gTUTEpqUXlhiYRyyEI4NV0TfFH0gMjfPE5a_oKUbqE9hPo9_cQdz3-zmwKZaWwlJjFnxz4HLDz3LlEI7K5CaXJGWTE_yiX39ra95-I2swhqLiFYy4e-N3iffCFPhx1jMg7BaCopOgGwncFf6qyoCqRrkS2WfG0DVoWQFL-n95CkGCYm8lEM-OIyCoHVj34vBEBJSL6SdfZgVq52LoQXkcIq6ropNDoSobP91Skc4vomvsSF1UTJe8-JVaunX-aGFNdMIolStxhePiiynDHB-1vJpjB0cPX3xHNZcjPZB_He4Fswx0QhY8WFT0iJL8BL2zGeq0R1MeIeYkuMQ1MWTe5mXGI0xHOugq2OHuAk5x2UWaR9To0RNZBV4BwHQM4pH9kbh1LmZOXkrtGD30Cd4FL7oaBoGxZLknxVm40)

**Comment by tozydev** [comment]
## Changes

- Loại bỏ MQH use case "Đăng nhập" của Staff.

<details><summary>Code</summary>

```plantuml
@startuml
skinparam usecase {
  BackgroundColor BUSINESS
}

skinparam note {
  BackgroundColor LightSkyBlue
}

left to right direction

actor Guest as G
actor Customer as C
actor Staff as S
actor Manager as M
actor "System Administrator" as AD

G <|-r- C
S <|-r- M

rectangle "System" as SS {
  note "Quản lý thường là CRUD\nCRUD: Create, Read, Update, Delete" as N2

  usecase "Đăng nhập" as UC5
  rectangle "User" as F {
    usecase "Tìm kiếm dịch vụ" as UC1
    usecase "Xem dịch vụ" as UC2
    usecase "Sử dụng trợ lý ảo" as UC3
    usecase "Đăng ký" as UC4
    usecase "Quản lý lịch hẹn" as UC6
    usecase "Đánh giá dịch vụ" as UC7
    usecase "Quản lý thông tin\ncá nhân" as UC8
    usecase "Xem lịch sử đặt hẹn" as UC20
  }

  rectangle "Admin" as B {
    usecase "Quản lý lịch hẹn\nkhách hàng" as UC9
    usecase "Xem lịch sử làm việc" as UC10
    usecase "Cập nhật trạng thái\n(vắng/có)" as UC11
    usecase "Tạo hóa đơn thanh toán" as UC12
    usecase "Phản hồi đánh giá" as UC13
    usecase "Quản lý dịch vụ" as UC14
    usecase "Quản lý nhân viên" as UC15
    usecase "Quản lý tài chính" as UC16
    usecase "Báo cáo và thống kê" as UC17
    usecase "Cập nhật thông tin\nsalon" as UC18
  }
}

F -[hidden]- B
N2 .r. B

G -d- UC1
G -d- UC2
G -d- UC3
G -d- UC4
G -d- UC5

C -d- UC6
C -d- UC7
C -d- UC8
C -d- UC20

S -u- UC9
S -u- UC10
S -u- UC11
S -u- UC12
S -u- UC13
S -u- UC14 : xem

M -u- UC14
M -u- UC15
M -u- UC16
M -u- UC17
M -u- UC18

AD -- SS : administer
@enduml
```
</details> 

Preview:

![ZLGnQzj06DtlLtnuQY5A4pkEdT0XiToOGXtQA8P2tU6GBfAmT0hIoJIacJfqwDBGkM0tP0aDBQHGQXCwNCZ_q3_fdIoTBTSkNSpJf_S-lNVty4x4SCXYtqDHpwN7ECG-n14nSKJW504qiDcpmo2cbXvuGGYDZl5q_ubXe3Cqew01Mqn_vjeECted3IycKkAH8mOiW53EmN93OZ8te0XXam](https://github.com/user-attachments/assets/3e25675c-c67e-4e3b-9ff4-ed1636df2d6c)
