### ISSUE TITLE
Vẽ biểu đồ UML Use case: Phân rã use case "Customer"

### ISSUE THREAD

**Issue by tozydev** [tozydev/virgo-14#5]
Công việc:

> Vẽ biểu đồ UML Use case: Phân rã use case "Customer"

Yêu cầu:

* Các công việc sẽ giúp hoàn thiện tài liệu `SRS.docx`.
* `SRS.docx` và tài liệu tham khảo tại [đây](https://drive.google.com/drive/folders/1NdWmfgmvmID0UyGiYH7Wz6Iz3QYg6vtS?usp=drive_link).
* Tạo ra các file riêng lẻ đối với từng yêu cầu, post link dưới phần `Comments` của từng task.
* Sau khi làm xong, kéo task sang phần `In Review`.
* Lưu các file output ở thư mục thành viên được tạo tương ứng.
* Đối với yêu cầu viết tài liệu, sử dụng `Google Docs` hoặc `Word`.
* Đối với vẽ sơ đồ, sử dụng draw.io hoặc phần mềm có thể xuất sang định dạng `.drawio`.

**Comment by tozydev** [comment]
Dựa vào Use Case tổng quan để phân rã ra theo yêu cầu. #4

**Comment by HuynhSang2005** [comment]
Link UML use case draw.io hoặc file draw trong thư mục member/Sang:
https://viewer.diagrams.net/?tags=%7B%7D&lightbox=1&highlight=0000ff&edit=_blank&layers=1&nav=1&title=Bi%E1%BB%83u%20%C4%91%E1%BB%93%20kh%C3%B4ng%20c%C3%B3%20ti%C3%AAu%20%C4%91%E1%BB%81.drawio#R%3Cmxfile%3E%3Cdiagram%20name%3D%22Trang-1%22%20id%3D%22pJtNp_zisobLCTBP_YYv%22%3EzVtdd6soFP01PrZLxI%2FwmI%2FeuS8z685q15reRyfSxLlGU2PS5P76AQVU0GpSDb60ggiy2Rz3OZwYcLk7%2F5H6%2B%2B2fSYAjwzKDswFXhmUB5FnkH625FDUzFxUVmzQMWKOy4jn8jVmlyWqPYYAPtYZZkkRZuK9XrpM4xuusVuenafJRb%2FaWRPVR9%2F4GKxXPaz9Sa%2F8Jg2zLZmF5Zf13HG62fGTA57fzeWM2k8PWD5KPShV8MuAyTZKsuNqdlzii4HFciue%2BtdwVL5biOOvzwOL9Bf36%2FeCZfvQSm%2B%2FoZB%2F%2Fe2C9nPzoyCZsWG5E%2Blv8Sy429GJ5PGTJDqf8BhlB3GMzyy4cLjIkWRlSWHxswww%2F7%2F01vfNByEHqttkuIiVALv3Dvliut%2FCMA9HVCacZPrfOEAjcCOEweassvZAm7AF3xqD%2BqKwUq9pWFonX%2BYwbG9FTCR%2B5YAhegSZsQFMCKE2OcUAnvDK7QRoAE8jmeuH8VCECttMAEgRjoeS2cu4tIZOqwuW%2BHxN%2B4%2BGQG4c5aQDs%2FTmHh98XfFzaBjLp3xmMN6RlvDWegLGYG%2FPVvkLgYqAWDpdLBO6yRI60RLBhiayGFXLHWiDUTWMcB3NqXUlpHfmHQ7iuw1KnOT6H2Wvl%2Bie9fnRYaXWu3FpdWKEYEgeKeZZgJa%2BVHNM17jZymZ9ucNZFTHWZKuvQtFF4XYojPwtP9ddtWhs2wo8kzNnONyqq0wBJq1vMkj1UNfNSP4IqrB9b6qdAQemHrKZ%2FqTTb0waH9tcFADQNU9Ku6LAkoQD0dl4CSyVmseGLPb7w6Auuiy2%2FMJCnfWsLGTOZvQ3s6X2jJAMoJl8BSeyOKkgCueFRchSUlpxWs1VM9SwvLQjfSENWnDvaOec6dTSRo6DZBKYzGpZeF5YUrPCQaUfOMs2JQTfrgi4Txm4VUm8p9GPtMEI4MRitHrr8SkETk%2Fd6LVUMLf6s3is1TV66XtR0ipXiY6hLrdju5yrjVrUCRpIr0Gx837bXsrzPmo%2BjbqBqJwdk6cyq8fTRdDuompd%2B4DQk8yLOvyTkhXj%2FyUa%2Bj5C3%2Bm4OT%2BfmsCRSK5at7%2B6QaSg%2BUB27YyhK8s04gif4CBxY8wbRzPuURrSg0HF0MzwgJR2dlASmpApvpSRwpI7uTcmmiKWWb3lJZWT1NoZNLNbCxplONsKhDCTUbSDViMTfRx5xhFSgR8YSGotVflXzGHlgcoH0K3ZXglF%2FmMKeYphC9msa4hR2E0rjxSlsNZb%2BinfTJpsj71mkwnhX99BWhffLNvcu8ugi4B62E04bWE8JX%2BgGVg1ffOdxMu8ybTDFCe9kwBzvVEaTM9eM%2F30UiCfFL4AsHPoqEE8OYMB%2BCuTaAIYyjnmHkAQHW7%2FYHpB3XLN1amRb63mgK5%2BKeLcyVP4syGpkZI3sTNBj02Lw%2BhNPa%2FRKdgYUkX%2BrabTkjJKxiac6Z4N9MRGoRq%2FAoynKN0WvXDk6C24Kz2ohq9ZIwkw2brceRMzkLBw5%2F2JssqpnVH%2BVuUtEDy%2FpqnH1TOMJgThyzjOdTjTQMCcvbb63RSAKdybkohtSR5Gs0dI1FiZ3cr7RznRrb9SiqbSFI5we4YjbTAmomJF7p0Tp2rSo%2BTDu6j2LZBE%2FkvaWx%2Bk4PJSbo%2Bua8xTNcZW9muDSGrikJoJc2rmZycKY51EG4YnnUK5z40OIQBMu6aUVV7ItKw212xYApmdcmhJiW2G6T6wTmLb0YXXUJI47BzsdNQKyrGb3VpN9s0be6uaeKUtrz3tUYRU5EFVYPWckVN0G96xMquRhz10N2V8CaHTUj6qFJojq8L7Hl51egCSfxbr%2BxH1ACcINSqeHUex7bSfnQHYxZJXR%2B%2BgcyD6G%2FEOUkX0Md%2Fg8OEEu1%2FWMrzrEOsjlalXCAHrwc0r0Jpec4Wa57n3JNbyLpD%2FJ0tGatNPid9xgeDocrqF%2BEyJn8n8tbZIUy19HFs3L35jCp%2F8B%3C%2Fdiagram%3E%3C%2Fmxfile%3E

**Comment by HuynhSang2005** [comment]
Link UML use case phân rã "Customer" từ draw.io hoặc trong thư mục member/Sang:
https://viewer.diagrams.net/?tags=%7B%7D&lightbox=1&highlight=0000ff&edit=_blank&layers=1&nav=1&title=UML_use-case_phan-ra-customerdrawio.drawio#R%3Cmxfile%3E%3Cdiagram%20name%3D%22Trang-1%22%20id%3D%22pJtNp_zisobLCTBP_YYv%22%3E1VzbdqQoFP0aH5Ml4vWxLunOy%2FT0rGStSR6d0pROW1qxrFt%2F%2FYCKImA0FS%2FMS0eQQtnsA%2Fscjq3A1e7yPXX3wR%2BJ50eKpnoXBa4VTdMAtNAfXHMtahxdKyq2aegVVaCueAp%2F%2B2WlWtYeQ88%2FNBpmSRJl4b5ZuUni2N9kjTo3TZNzs9lbEjWfune3PlfxtHEjvvbv0MuCotbWrLr%2B0Q%2B3AXkyMJ3izs4ljcuRHALXS85UFXxQ4CpNkqy42l1WfoTBI7gUv%2FvWcrd6sdSPsz4%2FWL4%2FO79%2B31mqGz3H6rtz0o%2F%2F3pW9nNzoWA5Y0cwI9bf8B11s8cXqeMiSnZ%2BSG%2BgJ1b1yZNmVwIUeiWYGFZbnIMz8p727wXfOiByoLsh2ESoBdOke9sV0vYUX36u6oodD3s1PM%2F9CVZXD%2B%2B6jt8rSK2pS3jXtEuozNVNlVUBNEqlzS25sq55q%2BNBFieAn0IQCNBmA0uQYe3jAa7UbpAEwgeVYr4SfPERANwQgQTAWSmYr594SNE4aLvP9mJAbd4d8cVigBkDfX3J4yP2KjytdcVT8rw3jLWoZB8oDUJYLZbHeUwQuHtTC4XqKwCRTZDBTBAVTpAlmyBxrgpxuGvuxt8CrKyptIvdwCDdNWJo09y9h9kJdv%2BLre6MsrS%2FUrfW1LLQCe0iO6cbvXtMyN936WTcPfa%2BxA%2FDTRM2DyFBIXepHbhaemvuGaG7KJ%2FxMwpztxFCdJg0cZnaLYZc%2Fopd5pp%2BKKmU%2FOtNPAQvXD5pN90o12%2BMGh%2FbXBQCIHlPTruiwJmEF6O28BBpPzMLgCxtfWvgFN4XJLxXHmt20KxkjjW0DXb49ilkAq8FTIFXWQYNUITc8SgaH0orQyl7HWM%2BS0hLxDTUsiwtjds6ZRhNNx%2BDQFIFpjIal1YUlBis8ZLMjp6mqZNDZXdBl1WK3DrG3FLrx7DBCKBmMWg9d%2FklBE6P3eqlVDC6%2B0vdqTZOXOkVNp1ghe58kakU3P1YZt6oVMJJcgarwfdteS7M%2Baj6OuoH8OjkgS22twdN71eygal766achGhdy%2FhkhX4n31%2FLJowh5ra9xWFIZh8aQmlvZ%2BloHS8Nqg%2BqwjqEoSYxxBE%2FwHhiw4Q06tvUhjXCBo%2BPQy%2FCAlDSkoiRQGVV4KyWBwXQ0NSVFEctZ9vKayo7WezEUsXgKNtpSsREOtUDCuRdIPiLx15FEHCEW6JGygspynV81PEYSmFw68yt2k4Fx%2FjCFLmOYgvVrBHEKXYTSeHEKnY%2Blv%2Fg7uclmsDbr8DBO6h7qvPB%2BDnLvIo8uAuJhG6HcwFpc%2BGJuYPnwxSOJk1lXucGsTnilAXO8U5lpnDlFJgViMfELwAqHvgrEYgMYsJ8C%2BWwAg3uOOkFIgoA9v9i%2BnXdEonVqZF2u80CTPRWxbmUouy2wamRkjWxI6LFNseD1J55c0SvWGeBE%2Fq1Lo8ZmlIxNPN45G2zHdAAdvQL3alW%2BKXplstFZcFN4dgqyyhVJsNnF7daDCJvNwmHzL8YmK39G9aPOXUJ6eIWnkahnHE%2FwqiPnPNPphAMNC%2FTS6ntbBKJwZ0IiuiF2FNEcrUxlqRIn5xvubG7tzYqz2cMRBp8P0BrnwYiiSz2flSyMSdqZF55IytkmnysEAs5Pw5daTCWnUQ1nnwoAHOnmQpQ%2FOHNoCKg6sw4Z%2FJn3xLEhg3cYV3QyJJ0bmQl5Ozf3VFaJWNY9D2t1ZEzDahkjoWoK1Gydg0aiRLsGsr8qoJ3j%2FKhqjoSoDi%2FVvuwjAIeReNrnDyhb56tTkJH1o1OQETOXRJABwCoyNiDS%2B6QRsJKMzdsfWZKZw6cNVeQyTUv5qv8wAblMuaJ2AFrwY0r0JhebEKSZ5rTk6nHAJXtOmiFXjoPTkfnef%2BERJ4sNnkLPJj4PnGWmorXi8Jg8X7dvweMC%2FAnUH6Hgg6%2FnwI3x6UuWFF7JIMKP0yMChrVKFF2f0ecQojaqPDEhba53KtkMbov%2BMMbYadntLJnLjg3VHsSODfbjC3KkN%2FwSLwRRIB%2FKz9NyM8M2tw2rSAD3QQEJ51AhAvVUtF%2FMb6Ocxzu%2FkUqzoxKZR04W%2Bn%2Fu1sd4B%2Fv%2BrQg5%2Ft93azZYONJm3fK6o%2B7VfNDxi4TuS7L5nEcwlIRr%2B%2FDuy2s%2FKtbf7BfN6%2F%2F5AD78Bw%3D%3D%3C%2Fdiagram%3E%3C%2Fmxfile%3E

**Comment by tozydev** [comment]
Xem lại cách vẽ UML Use Case, sai actor, sai relationship

**Comment by HoangHazaLHC** [comment]
File.doc mô tả quy trình sử dụng dịch vụ của CUSTOMERs
https://docs.google.com/document/d/18oRdmEexCpx0Al0gBAkD6fPvFf5Qerey/edit

**Comment by tozydev** [comment]
@HuynhSang2005 @HoangHazaLHC đã cập nhật lại [`Use case tổng quan`](#4) (#4).
Hãy cập nhật lại Biểu đồ này.

**Comment by tozydev** [comment]
Outcomes?

**Comment by HuynhSang2005** [comment]
> Outcomes?

đã update: https://drive.google.com/file/d/1S-ccer6c6moL6UPpQpIHaIySmb_aFQfM/view

**Comment by tozydev** [comment]
@HuynhSang2005 Chỗ use case "Đặt lịch" nên đổi lại thành "Chọn thời gian"

**Comment by HuynhSang2005** [comment]
> @HuynhSang2005 Chỗ use case "Đặt lịch" nên đổi lại thành "Chọn thời gian"

đã update

**Comment by tozydev** [comment]
## Changes

- Thêm use case `Xem điểm thưởng`.
- Đổi tên use case `Đặt chỗ` thành `Tạo lịch hẹn`.
- Đổi tên use case `Thay đổi lịch hẹn` thành `Dời lịch hẹn`.

<details><summary>Code UML</summary>

```plantuml
@startuml

left to right direction

actor "Customer" as C

rectangle "System" {
  usecase "Quản lý lịch hẹn" as UC1
  usecase "Xem lịch sử đặt hẹn" as UC2
  usecase "Đánh giá dịch vụ" as UC3
  usecase "Quản lý thông tin cá nhân" as UC4
  usecase "Tạo lịch hẹn" as UC6
  usecase "Xem lịch hẹn" as UC7
  usecase "Dời lịch hẹn" as UC8
  usecase "Hủy lịch hẹn" as UC9
  usecase "Chọn dịch vụ" as UC10
  usecase "Chọn nhân viên" as UC11
  usecase "Chọn thời gian" as UC12
  usecase "Xem điểm thưởng" as UC14
  usecase "Cập nhật thông tin" as UC15
  usecase "Đổi mật khẩu" as UC16
}

C -- UC1
C -- UC2
C -- UC3
C -- UC4

UC1 <.. UC6 : <<extends>>
UC1 <.. UC7 : <<extends>>
UC1 <.. UC8 : <<extends>>
UC1 <.. UC9 : <<extends>>

UC4 <.. UC14 : <<extends>>
UC4 <.. UC15 : <<extends>>
UC4 <.. UC16 : <<extends>>

UC6 <.. UC10 : <<include>>
UC6 <.. UC11 : <<include>>
UC6 <.. UC12 : <<include>>

@enduml
```
</details> 

Preview:
![Image](https://github.com/user-attachments/assets/13ed733b-957d-43a7-924f-453bcde79e17)
