### ISSUE TITLE
Vẽ biểu đồ UML Use case: Phân rã use case "Staff"

### ISSUE THREAD

**Issue by tozydev** [tozydev/virgo-14#6]
Công việc:

> Vẽ biểu đồ UML Use case: Phân rã use case "Staff"

Yêu cầu:

* Các công việc sẽ giúp hoàn thiện tài liệu `SRS.docx`.
* `SRS.docx` và tài liệu tham khảo tại [đây](https://drive.google.com/drive/folders/1NdWmfgmvmID0UyGiYH7Wz6Iz3QYg6vtS?usp=drive_link).
* Tạo ra các file riêng lẻ đối với từng yêu cầu, post link dưới phần `Comments` của từng task.
* Sau khi làm xong, kéo task sang phần `In Review`.
* Lưu các file output ở thư mục thành viên được tạo tương ứng.
* Đối với yêu cầu viết tài liệu, sử dụng `Google Docs` hoặc `Word`.
* Đối với vẽ sơ đồ, sử dụng draw.io hoặc phần mềm có thể xuất sang định dạng `.drawio`.

**Comment by tozydev** [comment]
Dựa vào Use Case tổng quan để phân rã ra theo yêu cầu. #4

**Comment by tozydev** [comment]
@yendn281 @Tmy175 đã cập nhật lại [`Use case tổng quan`](https://github.com/tozydev/virgo-14/issues/4#issuecomment-2399970785) https://github.com/tozydev/virgo-14/issues/4#issuecomment-2399970785.
Lưu ý hãy xem lại biểu đồ trước khi phân rã use case.

**Comment by yendn281** [comment]
Biểu đồ phân rã use case (staff![Image](https://github.com/user-attachments/assets/8d99b9c9-21f1-415f-8e69-8e05557c5221))
https://viewer.diagrams.net/?tags=%7B%7D&lightbox=1&highlight=0000ff&edit=_blank&layers=1&nav=1&title=Bi%E1%BB%83u%20%C4%91%E1%BB%93%20kh%C3%B4ng%20c%C3%B3%20ti%C3%AAu%20%C4%91%E1%BB%81.drawio#R%3Cmxfile%3E%3Cdiagram%20name%3D%22Trang-1%22%20id%3D%22EpvecNAgVyfd57rLj98C%22%3E7Vxbc5s4GP01PCaDEAh49CXbnW23m5220%2BSRgGzUYuTBsuPsr18JC4MEdoiLsWmbl6ALsjnfOdL5hBIDThbbd1mwjP%2BmEU4My4y2BpwalgVMx%2BS%2FRM3LrsZx3F3FPCOR7FRWfCL%2F4eJOWbsmEV4pHRmlCSNLtTKkaYpDptQFWUaf1W4zmqifugzmuFbxKQySeu1XErF4V%2BtZbln%2FJybzuPhkgPxdyyIoOssnWcVBRJ8rVfDOgJOMUra7WmwnOBHgFbjs7vvjQOv%2Bi2U4ZW1u%2BGeTffz815fnrw%2Fb99%2Fee8m7m%2B%2FbGznKJkjW8oFXLJjNDAslfNBxRDb8ci4ui6qnTK%2FhH6n0yx%2BWvRQI8udeisv1IhmFjGa8zwZnjHCMPwRPOLmnK8IITXmXJ8oYXVQ6jBIyFw2MLnltzBYJLwB%2BSdcsISme7KNu7j9a3Iu3B0ECe%2Bg5ZzFdYJa98C7yBiiDJdkKbVl%2BLmNfdIkrYUeyLpBsm%2B8HLgPCL2RM3hAfvxafGr58FC4GXhg%2Fx4ThT8sgFC3PXI8qZjOSJBOaiAjw%2B%2BBsNrPCkNevWEa%2F40pLhJ6QgzoC1FYRBaCOKLAaILXPBSmwfzZMoXlxTJ3BYwodFVP%2F4pii4WOq8tS%2BPKbu8DFVeep4zqUx9YaOKXJeX%2FX7xdSq%2B7L72LgDxnhkjGAqvkZeGhs%2BJLxkTGzDB8YEGiOQxsI2k12hFgmOElMhD6THCjlauOrOCvO1IFGUHIpdRtdphKMOHZhuGJyGYICGYMCzBcOqBeNzEQtA81hwrMcwqAQCiUCIXCUO8ngwKoMzwIBYakCsJnWgXgNi1yeYiGdtskgzFtM5TYPkrqzVcCn7fKAit8iB%2F4YZe5EpaLDmIVPCgreEPYjbbx1Zeqy0TLdy5LzwosAvvtxx8Pmz0HUW4hYsZEE2x%2BzVjvVwZjgJGNmo36T72NSd4KQQy3TJG9L9PDZlR7UzOJ2YmoOEDTrxG3TinE0ndQf5gBe8IpGLhzcOxeS0ksXRNG8TE5Upum1I0c8NBxgP3X02xaMpmT%2FfvFV3n%2F%2BulVU9B388rYeoEM3YF92%2Bx7vVRDblAUvnAwwRUEPkNIXI6zVEdTN7MESRGqJNoSJngIGw1LkLWQ2BsPt0wLBuuuqLfhqNxBavwDEJVisSqiCrMHEospeHauGxXM1FsVzC81KxhmspCUaRGeGmlMT3EfDEaPMsiAgfpJquOC70I8VFuFUbYd4eNxKicI8zwsEVdOnaXBQ76695C7%2BZRRWWOEcWuNYORH7CPSUpK0nqaVmavm7unlLeZFU2wrVx9otwYWgtbaAdDLWBch7vn%2FoHqA1%2FbmoDhddQ%2BxkCzQG8JM81esLijdKbea5vEwNtoHPzvM0G5oB5riaCZem6qW1fktrA1Dw5OHUO17fs9Ddw5%2BZ2m43ki3L7GIMP837Y3HauitvWqfO2zm2353m7zYb%2Bb273zG10RZbE1tO%2Bky2J3%2FO03eY8xYCpXbXeg0gody9krySjtE%2FOKPWtRrNfWheqqtB6GqTzj3GwrNH76veikJ7%2FePJ1T4UTvb5uQm%2FL11OaCqyiYBXnsIBj00e300B7AV95CmxrXqq2z9hWmcgFKplsp1dlgjbcuerDEfr7eOvih81Q0wE%2BFCwEWvJAarVE0jBZc1EVlXOlS%2FOZ1Qro%2BmS4P6NakTxd4lSXPG%2BWr5I9XgrX2WYves1BNG6bvWJK966jNBqPis%2Fow3V06Bf8ttOSd5Ss5q3p%2BRpdO5mQkHYIApj%2BrTaTtJ2SHP2AS32oA5NSOVTRkc5mK3yWiQs1bd79WiLr2KKXkjWRmiuIkwPHdZuXTrfrPyqrG%2FPWMn1XpS3sZqVHmtvTX8a0Xun11LLljmCfonKtX15UFRlYLlR1YHo9Z80XV5UJXHW56kpVrmba9OSovX%2F2VFU56PpU1eSxf1VVqYrqV08d%2BsHiD0o60BgA0FY1ZnejMa%2BrHNXTNIauUGO%2Fc65mjYHBKgx1ozC%2BiFmuZg2tbgSmn9M5dXsW%2BZrA3CsU2O9868AiNliBuS0FZpvGMYGJJcyz1G3MjnY1HH2bVc%2BZ2irMNTWFeW9VmLzxRnuGUwTHi%2BVf1e%2B6l%2F%2BbAN79Dw%3D%3D%3C%2Fdiagram%3E%3C%2Fmxfile%3E

**Comment by Tmy175** [comment]
Biểu đồ phân rã use case staff
![Image](https://github.com/user-attachments/assets/53404c6f-0517-4954-9879-e18b2eb47246)

https://viewer.diagrams.net/?tags=%7B%7D&lightbox=1&highlight=0000ff&edit=_blank&layers=1&nav=1&title=bi%E1%BB%83u%20%C4%91%E1%BB%93%20ph%C3%A2n%20r%C3%A3%20use%20case%20staff.drawio#R%3Cmxfile%3E%3Cdiagram%20name%3D%22Trang-1%22%20id%3D%22-8jyyYih-3f9w7m2hBRT%22%3E7VxZc6M4EP4t%2B%2BCqnQenAHGYRx%2FJzFbtzmSO2pl52pJBNqpgxIKcxPvrVwKBJYGPeBwfKfxi1BIN6v76kNR2D4wXz%2B8zmEZ%2FkRDFPcsIn3tg0rMs07VM9sUpq5Ji%2B6AkzDMcikFrwlf8HxJEQ1CXOES5MpASElOcqsSAJAkKqEKDWUae1GEzEqtPTeEcNQhfAxg3qd9xSKOSOrC8Nf0DwvOoerLp%2BmXPAlaDxUzyCIbkSSKB2x4YZ4TQ8mrxPEYxF14ll%2FK%2Buw299YtlKKH73HD%2FrU%2F6X%2BAXOk%2Fx9Pbz7O770OtbJZdHGC%2FFhMXL0lUlAcaFCZs1Rk8RpuhrCgPe88T0zWgRXcSsZbLLGY7jMYlJVtwHZrOZFQSMntOMPCCpJ3SnruOynuYUxKweUUbRs0QSU3qPyALRbMWGiF7Lt8tbntbaMSuRR5JmbEGDAhDzmtVaZuxCiO0FIgRvRoTCRAfGmSVqvzWJmt65Req8NZFa7rlF6r41kQLn3CL13ppIbevcIh3sIdIkHPJMibWCGOY5DlRJZmSZhIg%2FxGAtJpxs9UNu%2FOSNG6dqTp7lzsmqaj1j%2BmM9krV%2BSj3rm3hDvuceZZiJAmWCpukVuaERcjjMMxhi9khZs44H%2FLBN577vmgNnm85zsswCIaDBP5%2FGfeM2%2BfTHp8kytt%2Ffffx70DeFZCnM5ojuTrFQqCSaTQhJEHFaEFLRMhRDih%2FV9LQNNuIJ9wSzqdUIta0bR3WktqvyKGcubpPzSZ0TMFRGQMNwKZkGI4Y1uJKGpXxA3gB6LZnDse9fCvaPi9nKkkzZjm6A9nmxYW00hZ0It1sRvrcNncsUHA2%2FrobffQ0BGFocvTQ7qNbS5zeEV4Lu1cUE56JiwtEMwdSyn4szhCqhuxhD0LKhuvWGse9eFPaBlg15h2LfUrHvXBz2rdfD%2Fo1hmir%2BPds6IBSYL0Z%2FwfPqTcK7KJPQwgEwDjUJoJqEHlbObxL7bN2eOBx4ajx4uUVcHfjBJYP%2FaIsCS7ei86P%2F6rfZ3YGmrGqhI%2B%2B2uS1Y0YP80XbbrGaCeR%2F1bs3eaNgbgoS%2FRtEa9XyAWas3tnu%2B2RuD3tBMIkaY47LR0AQTCVVFDmM8T7hbYgLk1j%2FigsMBjIeiY4HDMN6kO9VvHUEZOuDtFl0YLbrQV8vH00Uz4flWqcIkhSqYqEcASnpwuR6404pgoQ5KhG6uTx%2FWwFX0YYIWhQD3lApphttxpZBJyjqS2lQmdKt%2Brk0XjWDQdixwWuNoOv8faMEIsfBPg1HADSAXzeGk6OPGYPBhj7ga5wXXr486xZX1YZ7UNpoHtJ%2BXSuAohT9pqqgympHPhz1EpccSXYXCkvn1qcjyVPcF%2FBYVOSdVUfPAd6OKQlVFj5UVOdeniEZcbzt4P63vah4TT2Ay%2FxgxAVydeD39FK2l%2BqYthT2GdFvXbW1n8Az5wCwn7MZcnnkKE0XQ7r9LXsc2CspMf8gXYvPp7%2Bwl2VsY1de7goUxIwntz%2BACx6ty6AcUPyKuBKk%2FL0oBea9pps9yR%2FlQ3pOQbAFjqe8RZhiyb6ZKSJcZLxzcOi6A6aYhT0LYvNM2yskbMaIMNH02%2FQAzr9q4k2QpyxwFS6ukcQj2Beo4uQZe1YcZohLxJKOaatFDM8ZsxvhXT0pQ2cvAUVQ2So95IlmovljNi81l%2BoAZO86zXJH1BbyUcQXgCx61fAXs2fUUBg%2FzAv59TcmW45T6lS%2FeSdMIUUAytignSZ9GOHhIUC7eHSeY4kp4%2BlhJ0VvHSa%2BjjAtxnsZwVfXEmEnPMn7Di5RkFHKJF8qOCaSafCs0s6u5%2BIYLLoe42cJJEC9DVBPVG6qWuPGuNJyaq2RX68vNO1AkRUmxd1QVyppc%2BSHMo8Ilmdu2pl5jX6hx4nvI6XG5D7HRQfaNmwFwLTUZsJohyD3O%2Fo%2BtnWH5flUv8dIdIMfbxWnDFtCaUzWQzGY5UsYcsAnU6u3bSiQ6b995%2B87bd95eqjiSTvqsmlCeUHCHueNwo%2B2M7qQBxBsYnhpA3JMFEHNwtAjSwmpnCFm1TuP1AkprrVEXUbqI0kWULqKcaf1g%2B4apbrKAk7n%2Fej%2FnV51%2Fg9EFrB5a6%2Bk6Z985%2B87Zd86%2BbfkgLx3qisENy4bThggD%2BOoKwTxZiADu0VYILaz2XSH0T7dEaBZm%2FLLNXJcZ3ADPV1fRhucesopu%2Fz3F9iLy%2Fe1KrvHb9tO2X7U%2F48YyBmqG5rziAt1ST9z0k7S9bc%2FVVueXuL%2FbWuTXZWhdhtZlaF2Gtv0npTtKz9fBTNsRPlpatzP8eHuGn7JgZFv6BxxLO2F8xfRPiz82ODz9G%2BxkdQkxqPkfBDmFs1nDNPIIpvxyuYiHASVycc6fcIrie5Jj7iLYkCmhlCx6zeodSrTKdPFsvSCnBXGbAWJqNTot5ZttP0nQd2z2qNFhzfU%2FQpUKWP%2BvFrj9Hw%3D%3D%3C%2Fdiagram%3E%3C%2Fmxfile%3E

**Comment by tozydev** [comment]
@Tmy175 @yendn281 xem lại https://github.com/tozydev/virgo-14/issues/4#issuecomment-2401240587. 
- Phân rã ra các use case chi tiết (từng use case lớn sẽ có cái use case con nào, vd: "Quản lý lịch hẹn khách hàng" sẽ có "Từ chối lịch hẹn", "Chấp nhập lịch hẹn",...)
- Use case "Quản lí dịch vụ", Staff chỉ có thể xem, lưu ý thêm chữ "xem" vào mối quan hệ giữa Staff và "Quản lý dịch vụ".
- Không có use case "Cập nhật hóa đơn". 
- Bỏ use case "Đăng nhập"

**Comment by tozydev** [comment]
Use case không cần viết tài liệu mô tả

**Comment by yendn281** [comment]
https://drive.google.com/file/d/15lQQ_bCfHwHdEIAJCMuCMdO75qM0PmYx/view?usp=sharing

**Comment by tozydev** [comment]
- Phản hồi đánh giá: lược bớt các use case con, chỉ để use case lớn thôi vì nó đã rõ rồi.
- Tạo hóa đơn thanh toán: sẽ có 2 use case con (generalization), tạo mới hóa đơn dịch vụ (khách hàng đến sử dụng dịch vụ ko thông qua app), tạo hóa đơn theo lịch hẹn (dành cho khách book qua app).
- Cập nhật trạng thái nhân viên: vắng mặt/có mặt
- Xem lịch sử làm việc: ko cần thêm use case con
- Quản lí lịch hẹn khách hàng: xem/chấp nhận/hủy bỏ/dời lịch hẹn.
- Quản lí dịch vụ: staff chỉ đc xem dịch vụ.

**Comment by yendn281** [comment]
https://drive.google.com/file/d/15lQQ_bCfHwHdEIAJCMuCMdO75qM0PmYx/view?usp=drive_link

**Comment by yendn281** [comment]
https://drive.google.com/file/d/15lQQ_bCfHwHdEIAJCMuCMdO75qM0PmYx/view?usp=drive_link

**Comment by tozydev** [comment]
## Changes

<details><summary>Code UML</summary>

```plantuml
@startuml

left to right direction

actor Staff as S

rectangle System {
  usecase "Phản hồi đánh giá" as UC1
  usecase "Tạo hóa đơn\nthanh toán" as UC2
  usecase "Cập nhật trạng thái" as UC3
  usecase "Xem lịch sử\nlàm việc" as UC4
  usecase "Quản lý lịch hẹn\nkhách hàng" as UC5
  usecase "Xem dịch vụ" as UC6
  usecase "Tạo mới hóa đơn\ndịch vụ" as UC7
  usecase "Tạo hóa đơn\ntheo lịch hẹn" as UC8
  usecase "Có mặt" as UC9
  usecase "Vắng mặt" as UC10
  usecase "Xem lịch hẹn" as UC11
  usecase "Chấp nhận\nlịch hẹn" as UC12
  usecase "Dời lịch hẹn" as UC13
  usecase "Hủy lịch hẹn" as UC14
}

UC2 <|-- UC7
UC2 <|-- UC8

UC3 <.. UC9 : <<extends>>
UC3 <.. UC10 : <<extends>>

UC5 <.. UC11 : <<extends>>
UC5 <.. UC12 : <<extends>>
UC5 <.. UC13 : <<extends>>
UC5 <.. UC14 : <<extends>>

S -- UC1
S -- UC2
S -- UC3
S -- UC4
S -- UC5
S -- UC6

@enduml
```
</details> 

Preview:
![XP8_YzH06CRx-HGlrzznsMJFKy9nS1QMIbGihXcoivd1P2B9cyD5hIsin5A43R9OBHPRY1ciHlmUyqsSh1EOx1-iyWw_v-5vvfrSrqWhR8gSa9pD4R24IcGSOIOgbg8e9I4qnRA21Eby3hI6X90UKPdb3995ZQo0DmIWgLbAQmOdZxdflahWHdqIyFkZRYM7JEZsf7S_kmbyxLFJjILmlQ](https://github.com/user-attachments/assets/fc075e22-fd80-4676-8726-026fed544fe0)

**Comment by Tmy175** [comment]
![Image](https://github.com/user-attachments/assets/3eed5a54-f5a8-4829-b0b5-24491e67f8b1)
