### ISSUE TITLE
Quy trình sử dụng phần mềm của “Customer”

### ISSUE THREAD

**Issue by tozydev** [tozydev/virgo-14#9]
Công việc:

> Viết mô tả và vẽ sơ đồ UML Active.

Yêu cầu:

* Các công việc sẽ giúp hoàn thiện tài liệu `SRS.docx`.
* `SRS.docx` và tài liệu tham khảo tại [đây](https://drive.google.com/drive/folders/1NdWmfgmvmID0UyGiYH7Wz6Iz3QYg6vtS?usp=drive_link).
* Tạo ra các file riêng lẻ đối với từng yêu cầu, post link dưới phần `Comments` của từng task.
* Sau khi làm xong, kéo task sang phần `In Review`.
* Lưu các file output ở thư mục thành viên được tạo tương ứng.
* Đối với yêu cầu viết tài liệu, sử dụng `Google Docs` hoặc `Word`.
* Đối với vẽ sơ đồ, sử dụng draw.io hoặc phần mềm có thể xuất sang định dạng `.drawio`.

**Comment by HuynhSang2005** [comment]
Link quy trình sử dụng phần mềm của “Customer:
https://docs.google.com/document/d/19GhqVdlr2N4tVXjxAlvV_01midofz-8lqW-Rm2lGAt4/edit?usp=sharing

**Comment by tozydev** [comment]
Viết quy trình ngắn gọn dựa trên template, thiếu sơ đồ UML Active. Chủ yếu xem quy trình sẽ dựa vào biểu đồ. Còn nội dung mô tả ở mức tối thiểu.

**Comment by tozydev** [comment]
@HuynhSang2005 than khảo #10

**Comment by HuynhSang2005** [comment]
Link UML active quy trình sử dụng phần mềm của “Customer”: https://drive.google.com/file/d/1r2omfDLrYQxwU8HaaBu_4QlpHr59_TDf/view?usp=drive_link
Link docs mô tải quy trình sử dụng phần mềm của “Customer”: 
https://docs.google.com/document/d/19GhqVdlr2N4tVXjxAlvV_01midofz-8lqW-Rm2lGAt4/edit?usp=sharing
